### ISSUE TITLE
[ Help ] Works fine on my Atheros AR9565 wireless card but bluetooth

### ISSUE THREAD

**Issue by ghost** [FIRSTPLATO/opencore-atheros-kext#5]
**Thanks for your effort !**

I'm using [AR9565 AirPortAtheros40-9565.kext.zip](https://github.com/FIRSTPLATO/opencore-atheros-kext/raw/main/kext/AirPortAtheros40-9565.kext.zip) with *Atheros AR 9565 wireless card* on macOS BigSur . 

#### Throuble
This kernel extension works fine on my wireless module while the **`bluetooth`** module doesn't work, which leads to :
+ AirDrop 

do not work properly.

#### Detail
Device: `ASUS X540UP` -  i5 KabyLake

All codes are available from [Here](https://gitee.com/xjy37-me/OpenCore-EFI-ASUS.git) (known me if unavailable or too slow) as command:
```
git clone https://gitee.com/xjy37-me/OpenCore-EFI-ASUS.git -b X540UP
```
It't will be fine to get your genuine help.

**Comment by ghost** [comment]
sorry for changed username for sirius2. So [repo](https://gitee.com/Sirius2/OpenCore-EFI-ASUS) updated to 
```
git clone https://gitee.com/Sirius2/OpenCore-EFI-ASUS.git -b X540UP
```
and are available at [github synchronized repo](https://github.com/xjy37-me/OpenCore-EFI-ASUS)

**Comment by ipang-dwi** [comment]
Sorry to inform you that I don't have that wifi card, so I can't help right now. I will try to ask my friends, maybe someone of them have that wifi card. :)

**Comment by ipang-dwi** [comment]
For now, I just use AR9485 and MacOSX Catalina as daily os.. Ups, my mistake, my second daily os I mean.. My daily os still mx linux.. :)

**Comment by ghost** [comment]
Yeah... thanks ! Even though, feel free to it beacuse that pc is my *roommate‘s* and it‘s very close to perfect which means enough for daily use in present  :)
